#!/bin/bash

bash -c 'LD_LIBRARY_PATH=/lib:/usr/lib:. LD_PRELOAD=../../src/libelfperf/libelfperf.so:/tools/lib/libdl.so.2 ELFPERF_ENABLE=true \
ELFPERF_PROFILE_FUNCTION=\
__ctype_b_loc\
:__ctype_get_mb_cur_max\
:__ctype_tolower_loc\
:__ctype_toupper_loc\
:__cxa_atexit\
:__errno_location\
:__fpending\
:__getdelim\
:__libc_start_main\
:__overflow\
:__xstat64\
:_exit\
:abort\
:bindtextdomain\
:calloc\
:clock_gettime\
:clock_settime\
:dcgettext\
:error\
:exit\
:fclose\
:fopen64\
:fprintf\
:fputc\
:fputs_unlocked\
:free\
:fwrite\
:getenv\
:gettimeofday\
:iswprint\
:localtime\
:malloc\
:mbrtowc\
:mbsinit\
:memcpy\
:memset\
:mktime\
:nl_langinfo\
:printf\
:putenv\
:realloc\
:setenv\
:setlocale\
:settimeofday\
:sprintf\
:stpcpy\
:strchr\
:strcmp\
:strftime\
:strlen\
:strncmp\
:strrchr\
:textdomain\
:time\
:unsetenv\
  /tools/lib/ld-2.11.3.so /bin/date'
