#!/bin/bash

bash -c 'LD_LIBRARY_PATH=/lib:/usr/lib:. LD_PRELOAD=../../src/libelfperf/libelfperf.so:/tools/lib/libdl.so.2 ELFPERF_ENABLE=true \
ELFPERF_PROFILE_FUNCTION=\
:IceAddConnectionWatch\
:IceConnectionNumber\
:IceGetConnectionContext\
:IceProcessMessages\
:IceSetErrorHandler\
:IceSetIOErrorHandler\
:JSClassCreate\
:JSContextGetGlobalObject\
:JSObjectCallAsFunction\
:JSObjectGetPrivate\
:JSObjectGetProperty\
:JSObjectGetPropertyAtIndex\
:JSObjectMake\
:JSObjectMakeFunctionWithCallback\
:JSObjectSetProperty\
:JSStringCreateWithUTF8CString\
:JSStringGetMaximumUTF8CStringSize\
:JSStringGetUTF8CString\
:JSStringRelease\
:JSValueIsObject\
:JSValueIsString\
:JSValueIsUndefined\
:JSValueMakeBoolean\
:JSValueMakeString\
:JSValueMakeUndefined\
:JSValueToNumber\
:JSValueToObject\
:JSValueToStringCopy\
:NSS_Init\
:NSS_Shutdown\
:PK11_Authenticate\
:PK11_CipherOp\
:PK11_CreateContextBySymKey\
:PK11_DestroyContext\
:PK11_Finalize\
:PK11_FindFixedKey\
:PK11_FreeSlot\
:PK11_FreeSymKey\
:PK11_GetBlockSize\
:PK11_ParamFromAlgid\
:PK11_SetPasswordFunc\
:PL_strdup\
:PORT_Alloc\
:PORT_ArenaAlloc\
:PORT_FreeArena\
:PORT_NewArena\
:SECITEM_FreeItem\
:SECITEM_ZfreeItem\
:SECMOD_OpenUserDB\
:SECOID_AlgorithmIDTemplate\
:SEC_QuickDERDecodeItem\
:SmcCloseConnection\
:SmcDeleteProperties\
:SmcGetIceConnection\
:SmcInteractDone\
:SmcInteractRequest\
:SmcOpenConnection\
:SmcRequestSaveYourself\
:SmcSaveYourselfDone\
:SmcSetErrorHandler\
:SmcSetProperties\
:SmcVendor\
:XChangeProperty\
:XCreateWindow\
:XDestroyWindow\
:XInternAtom\
:XWindowEvent\
:_SOUP_METHOD_GET\
:_SOUP_URI_SCHEME_HTTP\
:_SOUP_URI_SCHEME_HTTPS\
:__errno_location\
:__isoc99_sscanf\
:__libc_start_main\
:__strdup\
:__xmlIndentTreeOutput\
:__xmlLoadExtDtdDefaultValue\
:access\
:avahi_address_snprint\
:avahi_client_errno\
:avahi_string_list_serialize\
:backtrace\
:backtrace_symbols_fd\
:bind_textdomain_codeset\
:bindtextdomain\
:cairo_destroy\
:cairo_fill\
:cairo_move_to\
:cairo_paint\
:cairo_rectangle\
:cairo_set_line_width\
:cairo_set_source_rgb\
:cairo_stroke_preserve\
:close\
:dbus_bus_add_match\
:dbus_connection_add_filter\
:dbus_connection_remove_filter\
:dbus_connection_send_with_reply\
:dbus_connection_set_exit_on_disconnect\
:dbus_error_free\
:dbus_error_init\
:dbus_error_is_set\
:dbus_g_bus_get\
:dbus_g_connection_flush\
:dbus_g_connection_get_connection\
:dbus_g_connection_register_g_object\
:dbus_g_connection_unref\
:dbus_g_object_type_install_info\
:dbus_g_proxy_begin_call\
:dbus_g_proxy_call\
:dbus_g_proxy_end_call\
:dbus_g_proxy_new_for_name\
:dbus_g_thread_init\
:dbus_glib_marshal_ephy_activation_BOOLEAN__BOXED_STRING_UINT_POINTER\
:dbus_glib_marshal_ephy_activation_BOOLEAN__STRING_UINT_POINTER\
:dbus_glib_marshal_ephy_activation_BOOLEAN__UINT_POINTER\
:dbus_message_get_args\
:dbus_message_get_type\
:dbus_message_is_signal\
:dbus_message_new_method_call\
:dbus_message_unref\
:dbus_pending_call_set_notify\
:dbus_pending_call_steal_reply\
:dbus_pending_call_unref\
:dcgettext\
:dcngettext\
:ephy_marshal_BOOLEAN__ENUM_STRING_STRING_STRING\
:exit\
:fclose\
:fcntl\
:feof\
:fgets\
:fopen\
:free\
:g_app_info_get_default_for_type\
:g_app_info_get_name\
:g_app_info_get_type\
:g_app_info_launch\
:g_app_launch_context_get_type\
:g_array_append_vals\
:g_array_free\
:g_array_insert_vals\
:g_array_new\
:g_array_remove_index\
:g_array_sized_new\
:g_array_sort_with_data\
:g_ascii_dtostr\
:g_ascii_formatd\
:g_ascii_strcasecmp\
:g_ascii_strdown\
:g_ascii_strncasecmp\
:g_ascii_strtod\
:g_ascii_strtoull\
:g_ascii_table\
:g_assertion_message\
:g_assertion_message_expr\
:g_atexit\
:g_atomic_pointer_get\
:g_atomic_pointer_set\
:g_base64_decode\
:g_boxed_type_register_static\
:g_build_filename\
:g_byte_array_append\
:g_byte_array_free\
:g_byte_array_sized_new\
:g_cclosure_marshal_VOID__BOXED\
:g_cclosure_marshal_VOID__ENUM\
:g_cclosure_marshal_VOID__FLOAT\
:g_cclosure_marshal_VOID__INT\
:g_cclosure_marshal_VOID__OBJECT\
:g_cclosure_marshal_VOID__POINTER\
:g_cclosure_marshal_VOID__STRING\
:g_cclosure_marshal_VOID__VOID\
:g_clear_error\
:g_compute_checksum_for_string\
:g_content_type_get_description\
:g_convert\
:g_desktop_app_info_new\
:g_dir_close\
:g_dir_open\
:g_dir_read_name\
:g_direct_equal\
:g_direct_hash\
:g_dpgettext\
:g_dpgettext2\
:g_enum_get_value\
:g_enum_get_value_by_nick\
:g_enum_register_static\
:g_error_free\
:g_error_new\
:g_file_copy\
:g_file_delete\
:g_file_enumerate_children\
:g_file_enumerator_close\
:g_file_enumerator_next_file\
:g_file_error_quark\
:g_file_get_basename\
:g_file_get_contents\
:g_file_get_parent\
:g_file_get_path\
:g_file_get_uri\
:g_file_has_prefix\
:g_file_info_get_content_type\
:g_file_info_get_file_type\
:g_file_info_get_name\
:g_file_make_directory\
:g_file_monitor_cancel\
:g_file_monitor_directory\
:g_file_monitor_file\
:g_file_monitor_get_type\
:g_file_move\
:g_file_new_for_commandline_arg\
:g_file_new_for_path\
:g_file_new_for_uri\
:g_file_query_exists\
:g_file_query_info\
:g_file_replace_async\
:g_file_replace_finish\
:g_file_set_contents\
:g_file_test\
:g_filename_display_basename\
:g_filename_from_uri\
:g_filename_from_utf8\
:g_filename_to_uri\
:g_filename_to_utf8\
:g_find_program_in_path\
:g_flags_get_first_value\
:g_flags_get_value_by_nick\
:g_flags_register_static\
:g_format_size_for_display\
:g_free\
:g_get_home_dir\
:g_get_host_name\
:g_get_language_names\
:g_get_prgname\
:g_get_tmp_dir\
:g_get_user_config_dir\
:g_get_user_name\
:g_get_user_special_dir\
:g_getenv\
:g_hash_table_destroy\
:g_hash_table_foreach\
:g_hash_table_foreach_remove\
:g_hash_table_insert\
:g_hash_table_lookup\
:g_hash_table_lookup_extended\
:g_hash_table_new\
:g_hash_table_new_full\
:g_hash_table_remove\
:g_hash_table_remove_all\
:g_hash_table_replace\
:g_hash_table_size\
:g_hash_table_steal\
:g_hash_table_unref\
:g_idle_add\
:g_idle_add_full\
:g_intern_static_string\
:g_io_add_watch\
:g_io_channel_unix_new\
:g_io_channel_unref\
:g_irepository_get_option_group\
:g_key_file_free\
:g_key_file_get_boolean\
:g_key_file_get_double\
:g_key_file_get_groups\
:g_key_file_get_keys\
:g_key_file_get_locale_string\
:g_key_file_get_locale_string_list\
:g_key_file_get_start_group\
:g_key_file_get_string\
:g_key_file_get_string_list\
:g_key_file_get_value\
:g_key_file_has_group\
:g_key_file_has_key\
:g_key_file_load_from_data\
:g_key_file_load_from_data_dirs\
:g_key_file_load_from_dirs\
:g_key_file_load_from_file\
:g_key_file_new\
:g_key_file_set_double\
:g_key_file_set_string\
:g_key_file_set_value\
:g_key_file_to_data\
:g_list_append\
:g_list_copy\
:g_list_delete_link\
:g_list_find\
:g_list_find_custom\
:g_list_first\
:g_list_foreach\
:g_list_free\
:g_list_index\
:g_list_insert_sorted\
:g_list_last\
:g_list_length\
:g_list_nth_data\
:g_list_position\
:g_list_prepend\
:g_list_remove\
:g_list_reverse\
:g_list_sort\
:g_listenv\
:g_locale_from_utf8\
:g_locale_to_utf8\
:g_log\
:g_log_default_handler\
:g_log_set_default_handler\
:g_log_set_handler\
:g_malloc\
:g_malloc0\
:g_malloc_n\
:g_markup_printf_escaped\
:g_match_info_fetch_named\
:g_match_info_fetch_pos\
:g_match_info_free\
:g_match_info_matches\
:g_match_info_next\
:g_memdup\
:g_mkdir_with_parents\
:g_mkstemp\
:g_module_close\
:g_module_error\
:g_module_make_resident\
:g_module_open\
:g_module_symbol\
:g_node_child_position\
:g_node_children_foreach\
:g_node_destroy\
:g_node_insert\
:g_node_n_children\
:g_node_new\
:g_node_nth_child\
:g_node_unlink\
:g_object_add_weak_pointer\
:g_object_class_find_property\
:g_object_class_install_property\
:g_object_class_override_property\
:g_object_connect\
:g_object_freeze_notify\
:g_object_get\
:g_object_get_data\
:g_object_get_property\
:g_object_get_qdata\
:g_object_interface_install_property\
:g_object_new\
:g_object_notify\
:g_object_ref\
:g_object_ref_sink\
:g_object_remove_weak_pointer\
:g_object_set\
:g_object_set_data\
:g_object_set_data_full\
:g_object_set_property\
:g_object_set_qdata\
:g_object_steal_data\
:g_object_thaw_notify\
:g_object_unref\
:g_object_weak_ref\
:g_object_weak_unref\
:g_once_init_enter_impl\
:g_once_init_leave\
:g_option_context_add_group\
:g_option_context_free\
:g_option_context_new\
:g_option_context_parse\
:g_option_context_set_main_group\
:g_option_group_add_entries\
:g_option_group_new\
:g_option_group_set_parse_hooks\
:g_option_group_set_translation_domain\
:g_output_stream_close_async\
:g_output_stream_close_finish\
:g_output_stream_get_type\
:g_output_stream_write_async\
:g_output_stream_write_finish\
:g_param_spec_boolean\
:g_param_spec_boxed\
:g_param_spec_enum\
:g_param_spec_flags\
:g_param_spec_float\
:g_param_spec_int\
:g_param_spec_int64\
:g_param_spec_object\
:g_param_spec_pointer\
:g_param_spec_string\
:g_param_spec_uint\
:g_path_get_basename\
:g_path_get_dirname\
:g_path_is_absolute\
:g_print\
:g_propagate_error\
:g_ptr_array_add\
:g_ptr_array_foreach\
:g_ptr_array_free\
:g_ptr_array_new\
:g_ptr_array_remove_fast\
:g_ptr_array_remove_index\
:g_ptr_array_remove_index_fast\
:g_ptr_array_set_size\
:g_ptr_array_sized_new\
:g_ptr_array_sort\
:g_quark_from_static_string\
:g_quark_from_string\
:g_queue_find_custom\
:g_queue_foreach\
:g_queue_free\
:g_queue_is_empty\
:g_queue_new\
:g_queue_pop_head\
:g_queue_push_head\
:g_queue_push_tail\
:g_queue_remove\
:g_random_int\
:g_regex_escape_string\
:g_regex_match\
:g_regex_new\
:g_regex_replace\
:g_regex_unref\
:g_return_if_fail_warning\
:g_set_application_name\
:g_set_error\
:g_set_prgname\
:g_setenv\
:g_shell_parse_argv\
:g_shell_quote\
:g_signal_accumulator_true_handled\
:g_signal_connect_data\
:g_signal_connect_object\
:g_signal_emit\
:g_signal_emit_by_name\
:g_signal_handler_block\
:g_signal_handler_disconnect\
:g_signal_handler_is_connected\
:g_signal_handler_unblock\
:g_signal_handlers_block_matched\
:g_signal_handlers_disconnect_matched\
:g_signal_handlers_unblock_matched\
:g_signal_has_handler_pending\
:g_signal_lookup\
:g_signal_new\
:g_signal_stop_emission_by_name\
:g_slice_alloc\
:g_slice_alloc0\
:g_slice_free1\
:g_slist_append\
:g_slist_concat\
:g_slist_delete_link\
:g_slist_find\
:g_slist_find_custom\
:g_slist_foreach\
:g_slist_free\
:g_slist_free_1\
:g_slist_last\
:g_slist_length\
:g_slist_nth_data\
:g_slist_prepend\
:g_slist_remove\
:g_slist_remove_link\
:g_slist_reverse\
:g_snprintf\
:g_source_remove\
:g_spawn_async_with_pipes\
:g_spawn_command_line_sync\
:g_static_mutex_get_mutex_impl\
:g_str_equal\
:g_str_has_prefix\
:g_str_has_suffix\
:g_str_hash\
:g_strchomp\
:g_strchug\
:g_strcmp0\
:g_strconcat\
:g_strdelimit\
:g_strdup\
:g_strdup_printf\
:g_strdupv\
:g_strerror\
:g_strfreev\
:g_string_append\
:g_string_append_len\
:g_string_append_printf\
:g_string_assign\
:g_string_erase\
:g_string_free\
:g_string_insert\
:g_string_insert_c\
:g_string_new\
:g_string_new_len\
:g_string_printf\
:g_string_sized_new\
:g_string_truncate\
:g_strjoin\
:g_strjoinv\
:g_strndup\
:g_strrstr\
:g_strrstr_len\
:g_strsplit\
:g_strsplit_set\
:g_strstr_len\
:g_strv_get_type\
:g_strv_length\
:g_thread_functions_for_glib_use\
:g_thread_init\
:g_thread_use_default_impl\
:g_threads_got_initialized\
:g_timeout_add\
:g_timeout_add_full\
:g_timeout_add_seconds\
:g_timer_destroy\
:g_timer_elapsed\
:g_timer_new\
:g_timer_start\
:g_type_add_interface_static\
:g_type_check_class_cast\
:g_type_check_instance_cast\
:g_type_check_instance_is_a\
:g_type_check_value_holds\
:g_type_class_add_private\
:g_type_class_peek_parent\
:g_type_class_ref\
:g_type_class_unref\
:g_type_fundamental\
:g_type_instance_get_private\
:g_type_interface_peek\
:g_type_module_get_type\
:g_type_module_set_name\
:g_type_module_unuse\
:g_type_module_use\
:g_type_name\
:g_type_register_static\
:g_type_register_static_simple\
:g_unichar_isspace\
:g_unlink\
:g_unsetenv\
:g_uri_escape_string\
:g_uri_parse_scheme\
:g_utf8_casefold\
:g_utf8_collate\
:g_utf8_collate_key\
:g_utf8_get_char\
:g_utf8_normalize\
:g_utf8_offset_to_pointer\
:g_utf8_pointer_to_offset\
:g_utf8_skip\
:g_utf8_strchr\
:g_utf8_strlen\
:g_utf8_strncpy\
:g_utf8_strrchr\
:g_value_copy\
:g_value_dup_object\
:g_value_dup_string\
:g_value_get_boolean\
:g_value_get_boxed\
:g_value_get_double\
:g_value_get_flags\
:g_value_get_float\
:g_value_get_int\
:g_value_get_int64\
:g_value_get_long\
:g_value_get_object\
:g_value_get_pointer\
:g_value_get_string\
:g_value_get_uint\
:g_value_init\
:g_value_peek_pointer\
:g_value_set_boolean\
:g_value_set_double\
:g_value_set_enum\
:g_value_set_flags\
:g_value_set_float\
:g_value_set_int\
:g_value_set_int64\
:g_value_set_long\
:g_value_set_object\
:g_value_set_pointer\
:g_value_set_static_string\
:g_value_set_string\
:g_value_set_uint\
:g_value_take_boxed\
:g_value_take_object\
:g_value_take_string\
:g_value_unset\
:g_warn_message\
:ga_client_new\
:ga_client_start\
:ga_service_browser_attach\
:ga_service_browser_new\
:ga_service_resolver_attach\
:ga_service_resolver_new\
:gconf_client_add_dir\
:gconf_client_get\
:gconf_client_get_bool\
:gconf_client_get_default\
:gconf_client_get_default_from_schema\
:gconf_client_get_float\
:gconf_client_get_int\
:gconf_client_get_list\
:gconf_client_get_string\
:gconf_client_get_without_default\
:gconf_client_key_is_writable\
:gconf_client_notify\
:gconf_client_notify_add\
:gconf_client_notify_remove\
:gconf_client_preload\
:gconf_client_remove_dir\
:gconf_client_set_bool\
:gconf_client_set_float\
:gconf_client_set_int\
:gconf_client_set_list\
:gconf_client_set_string\
:gconf_client_suggest_sync\
:gconf_client_unset\
:gconf_entry_get_value\
:gconf_value_free\
:gconf_value_get_bool\
:gconf_value_get_float\
:gconf_value_get_int\
:gconf_value_get_list\
:gconf_value_get_list_type\
:gconf_value_get_string\
:gconf_value_new\
:gconf_value_set_list\
:gconf_value_set_string\
:gdk_app_launch_context_new\
:gdk_app_launch_context_set_display\
:gdk_app_launch_context_set_screen\
:gdk_app_launch_context_set_timestamp\
:gdk_atom_intern\
:gdk_atom_intern_static_string\
:gdk_atom_name\
:gdk_cairo_create\
:gdk_cairo_set_source_color\
:gdk_cairo_set_source_pixbuf\
:gdk_color_free\
:gdk_color_get_type\
:gdk_cursor_new\
:gdk_cursor_new_for_display\
:gdk_cursor_unref\
:gdk_display_get_default\
:gdk_display_get_default_screen\
:gdk_drag_status\
:gdk_drawable_get_colormap\
:gdk_drawable_get_type\
:gdk_drawable_set_colormap\
:gdk_event_copy\
:gdk_event_free\
:gdk_event_get_coords\
:gdk_event_get_root_coords\
:gdk_event_get_state\
:gdk_event_get_time\
:gdk_event_get_type\
:gdk_flush\
:gdk_notify_startup_complete\
:gdk_pixbuf_get_from_drawable\
:gdk_pixbuf_get_height\
:gdk_pixbuf_get_type\
:gdk_pixbuf_get_width\
:gdk_pixbuf_loader_close\
:gdk_pixbuf_loader_get_pixbuf\
:gdk_pixbuf_loader_new_with_type\
:gdk_pixbuf_loader_write\
:gdk_pixbuf_new\
:gdk_pixbuf_new_from_file\
:gdk_pixbuf_new_from_file_at_size\
:gdk_pixbuf_new_subpixbuf\
:gdk_pixbuf_scale_simple\
:gdk_pixmap_new\
:gdk_rectangle_intersect\
:gdk_screen_get_default\
:gdk_screen_get_display\
:gdk_screen_get_height\
:gdk_screen_get_monitor_at_point\
:gdk_screen_get_monitor_at_window\
:gdk_screen_get_monitor_geometry\
:gdk_screen_get_number\
:gdk_screen_get_width\
:gdk_screen_make_display_name\
:gdk_set_sm_client_id\
:gdk_threads_enter\
:gdk_threads_leave\
:gdk_window_at_pointer\
:gdk_window_get_origin\
:gdk_window_get_pointer\
:gdk_window_get_state\
:gdk_window_get_toplevel\
:gdk_window_get_user_data\
:gdk_window_set_cursor\
:gdk_x11_display_broadcast_startup_message\
:gdk_x11_display_get_user_time\
:gdk_x11_display_get_xdisplay\
:gdk_x11_window_set_user_time\
:getpid\
:getpwnam\
:gnome_keyring_find_network_password\
:gnome_keyring_item_delete\
:gnome_keyring_item_get_attributes\
:gnome_keyring_item_get_info_full\
:gnome_keyring_item_info_get_secret\
:gnome_keyring_item_info_get_type\
:gnome_keyring_list_item_ids\
:gnome_keyring_memory_free\
:gnome_keyring_memory_strdup\
:gnome_keyring_set_network_password\
:gnome_keyring_set_network_password_sync\
:gtk_accel_map_add_filter\
:gtk_accel_map_change_entry\
:gtk_accel_map_load\
:gtk_accel_map_save\
:gtk_accelerator_get_default_mod_mask\
:gtk_accelerator_parse\
:gtk_action_activate\
:gtk_action_create_tool_item\
:gtk_action_get_name\
:gtk_action_get_proxies\
:gtk_action_get_sensitive\
:gtk_action_get_type\
:gtk_action_group_add_action\
:gtk_action_group_add_action_with_accel\
:gtk_action_group_add_actions\
:gtk_action_group_add_radio_actions\
:gtk_action_group_add_toggle_actions\
:gtk_action_group_get_action\
:gtk_action_group_get_name\
:gtk_action_group_get_type\
:gtk_action_group_new\
:gtk_action_group_remove_action\
:gtk_action_group_set_translation_domain\
:gtk_action_is_sensitive\
:gtk_action_new\
:gtk_action_set_accel_group\
:gtk_action_set_accel_path\
:gtk_action_set_sensitive\
:gtk_action_set_visible\
:gtk_activatable_get_related_action\
:gtk_activatable_get_type\
:gtk_adjustment_get_page_increment\
:gtk_adjustment_get_page_size\
:gtk_adjustment_get_step_increment\
:gtk_adjustment_get_upper\
:gtk_adjustment_get_value\
:gtk_adjustment_set_value\
:gtk_alignment_get_type\
:gtk_alignment_new\
:gtk_alignment_set_padding\
:gtk_arrow_new\
:gtk_bin_get_child\
:gtk_bin_get_type\
:gtk_box_get_type\
:gtk_box_pack_end\
:gtk_box_pack_start\
:gtk_box_reorder_child\
:gtk_box_set_spacing\
:gtk_builder_add_from_file\
:gtk_builder_get_object\
:gtk_builder_new\
:gtk_builder_set_translation_domain\
:gtk_button_box_get_type\
:gtk_button_box_set_child_secondary\
:gtk_button_get_type\
:gtk_button_new\
:gtk_button_new_with_label\
:gtk_button_new_with_mnemonic\
:gtk_button_pressed\
:gtk_button_released\
:gtk_button_set_focus_on_click\
:gtk_button_set_image\
:gtk_button_set_label\
:gtk_button_set_relief\
:gtk_button_set_use_underline\
:gtk_cell_layout_add_attribute\
:gtk_cell_layout_get_cells\
:gtk_cell_layout_get_type\
:gtk_cell_layout_pack_end\
:gtk_cell_layout_pack_start\
:gtk_cell_layout_set_attributes\
:gtk_cell_layout_set_cell_data_func\
:gtk_cell_renderer_get_type\
:gtk_cell_renderer_pixbuf_new\
:gtk_cell_renderer_progress_new\
:gtk_cell_renderer_set_fixed_size\
:gtk_cell_renderer_text_get_type\
:gtk_cell_renderer_text_new\
:gtk_cell_renderer_text_set_fixed_height_from_font\
:gtk_cell_renderer_toggle_new\
:gtk_check_button_new_with_mnemonic\
:gtk_check_menu_item_get_active\
:gtk_check_menu_item_get_type\
:gtk_check_menu_item_new_with_mnemonic\
:gtk_check_menu_item_set_active\
:gtk_clipboard_get\
:gtk_clipboard_get_for_display\
:gtk_clipboard_get_owner\
:gtk_clipboard_request_text\
:gtk_clipboard_set_text\
:gtk_combo_box_append_text\
:gtk_combo_box_get_active\
:gtk_combo_box_get_active_iter\
:gtk_combo_box_get_model\
:gtk_combo_box_get_type\
:gtk_combo_box_new\
:gtk_combo_box_new_text\
:gtk_combo_box_new_with_model\
:gtk_combo_box_set_active\
:gtk_combo_box_set_active_iter\
:gtk_combo_box_set_focus_on_click\
:gtk_combo_box_set_model\
:gtk_combo_box_set_row_separator_func\
:gtk_container_add\
:gtk_container_forall\
:gtk_container_foreach\
:gtk_container_get_children\
:gtk_container_get_type\
:gtk_container_remove\
:gtk_container_set_border_width\
:gtk_dialog_add_action_widget\
:gtk_dialog_add_button\
:gtk_dialog_add_buttons\
:gtk_dialog_get_action_area\
:gtk_dialog_get_content_area\
:gtk_dialog_get_type\
:gtk_dialog_new_with_buttons\
:gtk_dialog_response\
:gtk_dialog_run\
:gtk_dialog_set_default_response\
:gtk_dialog_set_has_separator\
:gtk_dialog_set_response_sensitive\
:gtk_drag_begin\
:gtk_drag_check_threshold\
:gtk_drag_dest_add_text_targets\
:gtk_drag_dest_find_target\
:gtk_drag_dest_get_target_list\
:gtk_drag_dest_set\
:gtk_drag_finish\
:gtk_drag_get_data\
:gtk_drag_set_icon_default\
:gtk_drag_set_icon_pixmap\
:gtk_drag_source_get_target_list\
:gtk_drag_source_set\
:gtk_drag_source_set_icon_pixbuf\
:gtk_editable_copy_clipboard\
:gtk_editable_cut_clipboard\
:gtk_editable_delete_text\
:gtk_editable_get_chars\
:gtk_editable_get_editable\
:gtk_editable_get_position\
:gtk_editable_get_selection_bounds\
:gtk_editable_get_type\
:gtk_editable_insert_text\
:gtk_editable_paste_clipboard\
:gtk_editable_select_region\
:gtk_editable_set_editable\
:gtk_editable_set_position\
:gtk_entry_completion_delete_action\
:gtk_entry_completion_get_entry\
:gtk_entry_completion_get_model\
:gtk_entry_completion_insert_action_text\
:gtk_entry_completion_new\
:gtk_entry_completion_set_match_func\
:gtk_entry_completion_set_model\
:gtk_entry_completion_set_popup_completion\
:gtk_entry_completion_set_popup_single_match\
:gtk_entry_completion_set_text_column\
:gtk_entry_get_completion\
:gtk_entry_get_current_icon_drag_source\
:gtk_entry_get_text\
:gtk_entry_get_type\
:gtk_entry_new\
:gtk_entry_set_activates_default\
:gtk_entry_set_completion\
:gtk_entry_set_icon_activatable\
:gtk_entry_set_icon_drag_source\
:gtk_entry_set_icon_from_icon_name\
:gtk_entry_set_icon_from_pixbuf\
:gtk_entry_set_icon_from_stock\
:gtk_entry_set_icon_tooltip_text\
:gtk_entry_set_max_length\
:gtk_entry_set_progress_fraction\
:gtk_entry_set_text\
:gtk_entry_set_visibility\
:gtk_entry_set_width_chars\
:gtk_event_box_get_type\
:gtk_event_box_new\
:gtk_event_box_set_visible_window\
:gtk_expander_get_expanded\
:gtk_expander_get_type\
:gtk_expander_new\
:gtk_expander_set_expanded\
:gtk_expander_set_use_underline\
:gtk_file_chooser_add_filter\
:gtk_file_chooser_add_shortcut_folder\
:gtk_file_chooser_button_get_type\
:gtk_file_chooser_button_new_with_dialog\
:gtk_file_chooser_button_set_width_chars\
:gtk_file_chooser_dialog_get_type\
:gtk_file_chooser_get_current_folder\
:gtk_file_chooser_get_filename\
:gtk_file_chooser_get_preview_filename\
:gtk_file_chooser_get_type\
:gtk_file_chooser_get_uri\
:gtk_file_chooser_set_current_folder\
:gtk_file_chooser_set_current_name\
:gtk_file_chooser_set_do_overwrite_confirmation\
:gtk_file_chooser_set_extra_widget\
:gtk_file_chooser_set_filter\
:gtk_file_chooser_set_preview_widget\
:gtk_file_chooser_set_preview_widget_active\
:gtk_file_filter_add_mime_type\
:gtk_file_filter_add_pattern\
:gtk_file_filter_new\
:gtk_file_filter_set_name\
:gtk_frame_get_type\
:gtk_frame_new\
:gtk_frame_set_shadow_type\
:gtk_get_current_event\
:gtk_get_current_event_time\
:gtk_get_default_language\
:gtk_get_option_group\
:gtk_hbox_new\
:gtk_hbutton_box_new\
:gtk_hpaned_new\
:gtk_hseparator_new\
:gtk_icon_factory_add\
:gtk_icon_factory_add_default\
:gtk_icon_factory_new\
:gtk_icon_info_free\
:gtk_icon_info_get_base_size\
:gtk_icon_info_get_filename\
:gtk_icon_set_add_source\
:gtk_icon_set_new\
:gtk_icon_set_unref\
:gtk_icon_size_lookup_for_settings\
:gtk_icon_source_free\
:gtk_icon_source_new\
:gtk_icon_source_set_icon_name\
:gtk_icon_theme_append_search_path\
:gtk_icon_theme_get_default\
:gtk_icon_theme_get_for_screen\
:gtk_icon_theme_load_icon\
:gtk_icon_theme_lookup_icon\
:gtk_im_context_reset\
:gtk_image_get_icon_name\
:gtk_image_get_pixbuf\
:gtk_image_get_stock\
:gtk_image_get_storage_type\
:gtk_image_get_type\
:gtk_image_menu_item_get_type\
:gtk_image_menu_item_new_from_stock\
:gtk_image_menu_item_new_with_label\
:gtk_image_menu_item_new_with_mnemonic\
:gtk_image_menu_item_set_always_show_image\
:gtk_image_menu_item_set_image\
:gtk_image_new\
:gtk_image_new_from_icon_name\
:gtk_image_new_from_pixbuf\
:gtk_image_new_from_stock\
:gtk_image_set_from_pixbuf\
:gtk_image_set_from_stock\
:gtk_info_bar_get_action_area\
:gtk_info_bar_get_content_area\
:gtk_info_bar_get_type\
:gtk_info_bar_new\
:gtk_info_bar_new_with_buttons\
:gtk_info_bar_response\
:gtk_info_bar_set_message_type\
:gtk_label_get_type\
:gtk_label_new\
:gtk_label_new_with_mnemonic\
:gtk_label_set_ellipsize\
:gtk_label_set_label\
:gtk_label_set_line_wrap\
:gtk_label_set_markup\
:gtk_label_set_markup_with_mnemonic\
:gtk_label_set_max_width_chars\
:gtk_label_set_mnemonic_widget\
:gtk_label_set_selectable\
:gtk_label_set_single_line_mode\
:gtk_label_set_text\
:gtk_label_set_use_markup\
:gtk_label_set_use_underline\
:gtk_list_store_append\
:gtk_list_store_clear\
:gtk_list_store_get_type\
:gtk_list_store_insert_with_valuesv\
:gtk_list_store_new\
:gtk_list_store_remove\
:gtk_list_store_set\
:gtk_list_store_swap\
:gtk_main\
:gtk_main_level\
:gtk_main_quit\
:gtk_menu_get_type\
:gtk_menu_item_get_submenu\
:gtk_menu_item_get_type\
:gtk_menu_item_new_with_label\
:gtk_menu_item_new_with_mnemonic\
:gtk_menu_item_set_submenu\
:gtk_menu_new\
:gtk_menu_popup\
:gtk_menu_set_monitor\
:gtk_menu_shell_append\
:gtk_menu_shell_deactivate\
:gtk_menu_shell_deselect\
:gtk_menu_shell_get_type\
:gtk_menu_shell_insert\
:gtk_menu_shell_select_first\
:gtk_menu_tool_button_get_type\
:gtk_menu_tool_button_set_arrow_tooltip_text\
:gtk_menu_tool_button_set_menu\
:gtk_message_dialog_format_secondary_text\
:gtk_message_dialog_get_type\
:gtk_message_dialog_new\
:gtk_message_dialog_new_with_markup\
:gtk_misc_get_type\
:gtk_misc_set_alignment\
:gtk_misc_set_padding\
:gtk_notebook_get_current_page\
:gtk_notebook_get_n_pages\
:gtk_notebook_get_nth_page\
:gtk_notebook_get_tab_label\
:gtk_notebook_get_tab_pos\
:gtk_notebook_get_type\
:gtk_notebook_insert_page\
:gtk_notebook_next_page\
:gtk_notebook_page_num\
:gtk_notebook_remove_page\
:gtk_notebook_reorder_child\
:gtk_notebook_set_current_page\
:gtk_notebook_set_group\
:gtk_notebook_set_scrollable\
:gtk_notebook_set_show_border\
:gtk_notebook_set_show_tabs\
:gtk_notebook_set_tab_detachable\
:gtk_notebook_set_tab_reorderable\
:gtk_orientable_get_orientation\
:gtk_orientable_get_type\
:gtk_page_orientation_get_type\
:gtk_page_setup_get_bottom_margin\
:gtk_page_setup_get_left_margin\
:gtk_page_setup_get_orientation\
:gtk_page_setup_get_paper_size\
:gtk_page_setup_get_right_margin\
:gtk_page_setup_get_top_margin\
:gtk_page_setup_get_type\
:gtk_page_setup_new\
:gtk_page_setup_new_from_file\
:gtk_page_setup_set_bottom_margin\
:gtk_page_setup_set_left_margin\
:gtk_page_setup_set_orientation\
:gtk_page_setup_set_paper_size\
:gtk_page_setup_set_right_margin\
:gtk_page_setup_set_top_margin\
:gtk_page_setup_to_file\
:gtk_paned_get_position\
:gtk_paned_get_type\
:gtk_paned_pack1\
:gtk_paned_pack2\
:gtk_paned_set_position\
:gtk_paper_size_free\
:gtk_paper_size_get_display_name\
:gtk_paper_size_get_height\
:gtk_paper_size_get_name\
:gtk_paper_size_get_ppd_name\
:gtk_paper_size_get_width\
:gtk_paper_size_new_custom\
:gtk_paper_size_new_from_ppd\
:gtk_print_operation_new\
:gtk_print_operation_set_default_page_setup\
:gtk_print_run_page_setup_dialog_async\
:gtk_print_settings_new\
:gtk_print_settings_new_from_file\
:gtk_print_settings_to_file\
:gtk_propagate_event\
:gtk_radio_action_get_current_value\
:gtk_radio_action_get_group\
:gtk_radio_action_get_type\
:gtk_radio_action_set_group\
:gtk_radio_button_get_group\
:gtk_radio_button_get_type\
:gtk_radio_menu_item_get_group\
:gtk_radio_menu_item_get_type\
:gtk_radio_menu_item_new_with_label\
:gtk_rc_parse_string\
:gtk_recent_manager_add_item\
:gtk_recent_manager_get_default\
:gtk_scrolled_window_add_with_viewport\
:gtk_scrolled_window_get_type\
:gtk_scrolled_window_get_vadjustment\
:gtk_scrolled_window_new\
:gtk_scrolled_window_set_policy\
:gtk_selection_data_copy\
:gtk_selection_data_free\
:gtk_selection_data_get_data\
:gtk_selection_data_get_data_type\
:gtk_selection_data_get_length\
:gtk_selection_data_get_target\
:gtk_selection_data_get_text\
:gtk_selection_data_get_uris\
:gtk_selection_data_set\
:gtk_separator_menu_item_get_type\
:gtk_separator_menu_item_new\
:gtk_separator_tool_item_get_type\
:gtk_separator_tool_item_new\
:gtk_settings_get_default\
:gtk_settings_get_for_screen\
:gtk_show_about_dialog\
:gtk_show_uri\
:gtk_size_group_add_widget\
:gtk_size_group_new\
:gtk_spin_button_get_digits\
:gtk_spin_button_get_type\
:gtk_spin_button_get_value\
:gtk_spin_button_set_value\
:gtk_spin_button_update\
:gtk_status_icon_is_embedded\
:gtk_status_icon_new_from_stock\
:gtk_status_icon_position_menu\
:gtk_status_icon_set_tooltip_text\
:gtk_status_icon_set_visible\
:gtk_statusbar_get_context_id\
:gtk_statusbar_get_message_area\
:gtk_statusbar_get_type\
:gtk_statusbar_pop\
:gtk_statusbar_push\
:gtk_statusbar_set_has_resize_grip\
:gtk_stock_add_static\
:gtk_table_attach\
:gtk_table_attach_defaults\
:gtk_table_get_type\
:gtk_table_new\
:gtk_table_resize\
:gtk_table_set_col_spacing\
:gtk_table_set_col_spacings\
:gtk_table_set_row_spacings\
:gtk_target_list_add\
:gtk_target_list_new\
:gtk_target_list_unref\
:gtk_toggle_action_get_active\
:gtk_toggle_action_get_type\
:gtk_toggle_action_new\
:gtk_toggle_action_set_active\
:gtk_toggle_button_get_active\
:gtk_toggle_button_get_type\
:gtk_toggle_button_new\
:gtk_toggle_button_set_active\
:gtk_tool_button_get_type\
:gtk_tool_button_new\
:gtk_tool_button_new_from_stock\
:gtk_tool_button_set_label\
:gtk_tool_item_get_proxy_menu_item\
:gtk_tool_item_get_toolbar_style\
:gtk_tool_item_get_type\
:gtk_tool_item_new\
:gtk_tool_item_set_expand\
:gtk_tool_item_set_is_important\
:gtk_tool_item_set_proxy_menu_item\
:gtk_tool_item_set_tooltip_text\
:gtk_tool_item_set_use_drag_window\
:gtk_toolbar_get_drop_index\
:gtk_toolbar_get_item_index\
:gtk_toolbar_get_n_items\
:gtk_toolbar_get_nth_item\
:gtk_toolbar_get_type\
:gtk_toolbar_insert\
:gtk_toolbar_new\
:gtk_toolbar_set_drop_highlight_item\
:gtk_toolbar_set_show_arrow\
:gtk_toolbar_set_style\
:gtk_toolbar_unset_style\
:gtk_tooltip_set_markup\
:gtk_tree_model_filter_convert_child_iter_to_iter\
:gtk_tree_model_filter_convert_iter_to_child_iter\
:gtk_tree_model_filter_get_type\
:gtk_tree_model_filter_new\
:gtk_tree_model_filter_refilter\
:gtk_tree_model_filter_set_visible_func\
:gtk_tree_model_get\
:gtk_tree_model_get_column_type\
:gtk_tree_model_get_iter\
:gtk_tree_model_get_iter_first\
:gtk_tree_model_get_iter_from_string\
:gtk_tree_model_get_path\
:gtk_tree_model_get_type\
:gtk_tree_model_get_value\
:gtk_tree_model_iter_n_children\
:gtk_tree_model_iter_next\
:gtk_tree_model_row_changed\
:gtk_tree_model_row_deleted\
:gtk_tree_model_row_inserted\
:gtk_tree_model_rows_reordered\
:gtk_tree_model_sort_convert_child_iter_to_iter\
:gtk_tree_model_sort_convert_iter_to_child_iter\
:gtk_tree_model_sort_get_type\
:gtk_tree_model_sort_new_with_model\
:gtk_tree_path_append_index\
:gtk_tree_path_free\
:gtk_tree_path_get_depth\
:gtk_tree_path_get_indices\
:gtk_tree_path_new\
:gtk_tree_path_new_from_string\
:gtk_tree_path_next\
:gtk_tree_path_prev\
:gtk_tree_row_reference_free\
:gtk_tree_row_reference_get_model\
:gtk_tree_row_reference_get_path\
:gtk_tree_row_reference_new\
:gtk_tree_row_reference_valid\
:gtk_tree_selection_count_selected_rows\
:gtk_tree_selection_get_mode\
:gtk_tree_selection_get_selected\
:gtk_tree_selection_get_selected_rows\
:gtk_tree_selection_get_type\
:gtk_tree_selection_path_is_selected\
:gtk_tree_selection_select_all\
:gtk_tree_selection_select_iter\
:gtk_tree_selection_select_path\
:gtk_tree_selection_selected_foreach\
:gtk_tree_selection_set_mode\
:gtk_tree_selection_unselect_all\
:gtk_tree_sortable_get_type\
:gtk_tree_sortable_set_default_sort_func\
:gtk_tree_sortable_set_sort_column_id\
:gtk_tree_sortable_set_sort_func\
:gtk_tree_view_append_column\
:gtk_tree_view_column_add_attribute\
:gtk_tree_view_column_get_visible\
:gtk_tree_view_column_new\
:gtk_tree_view_column_new_with_attributes\
:gtk_tree_view_column_pack_start\
:gtk_tree_view_column_set_attributes\
:gtk_tree_view_column_set_cell_data_func\
:gtk_tree_view_column_set_expand\
:gtk_tree_view_column_set_min_width\
:gtk_tree_view_column_set_reorderable\
:gtk_tree_view_column_set_resizable\
:gtk_tree_view_column_set_sizing\
:gtk_tree_view_column_set_sort_column_id\
:gtk_tree_view_column_set_spacing\
:gtk_tree_view_column_set_title\
:gtk_tree_view_column_set_visible\
:gtk_tree_view_get_bin_window\
:gtk_tree_view_get_cell_area\
:gtk_tree_view_get_column\
:gtk_tree_view_get_dest_row_at_pos\
:gtk_tree_view_get_model\
:gtk_tree_view_get_path_at_pos\
:gtk_tree_view_get_selection\
:gtk_tree_view_get_type\
:gtk_tree_view_get_vadjustment\
:gtk_tree_view_get_visible_rect\
:gtk_tree_view_insert_column\
:gtk_tree_view_insert_column_with_attributes\
:gtk_tree_view_scroll_to_cell\
:gtk_tree_view_set_cursor\
:gtk_tree_view_set_drag_dest_row\
:gtk_tree_view_set_enable_search\
:gtk_tree_view_set_headers_visible\
:gtk_tree_view_set_model\
:gtk_tree_view_set_reorderable\
:gtk_tree_view_set_row_separator_func\
:gtk_tree_view_set_rules_hint\
:gtk_tree_view_set_search_column\
:gtk_tree_view_set_search_equal_func\
:gtk_ui_manager_add_ui\
:gtk_ui_manager_add_ui_from_file\
:gtk_ui_manager_add_ui_from_string\
:gtk_ui_manager_ensure_update\
:gtk_ui_manager_get_accel_group\
:gtk_ui_manager_get_action\
:gtk_ui_manager_get_action_groups\
:gtk_ui_manager_get_toplevels\
:gtk_ui_manager_get_type\
:gtk_ui_manager_get_widget\
:gtk_ui_manager_insert_action_group\
:gtk_ui_manager_new\
:gtk_ui_manager_new_merge_id\
:gtk_ui_manager_remove_ui\
:gtk_vbox_get_type\
:gtk_vbox_new\
:gtk_vpaned_new\
:gtk_vseparator_new\
:gtk_widget_add_events\
:gtk_widget_class_install_style_property\
:gtk_widget_create_pango_layout\
:gtk_widget_destroy\
:gtk_widget_ensure_style\
:gtk_widget_error_bell\
:gtk_widget_event\
:gtk_widget_get_allocation\
:gtk_widget_get_ancestor\
:gtk_widget_get_clipboard\
:gtk_widget_get_colormap\
:gtk_widget_get_default_direction\
:gtk_widget_get_direction\
:gtk_widget_get_display\
:gtk_widget_get_has_window\
:gtk_widget_get_mapped\
:gtk_widget_get_pango_context\
:gtk_widget_get_parent\
:gtk_widget_get_realized\
:gtk_widget_get_screen\
:gtk_widget_get_settings\
:gtk_widget_get_state\
:gtk_widget_get_style\
:gtk_widget_get_toplevel\
:gtk_widget_get_type\
:gtk_widget_get_visible\
:gtk_widget_get_visual\
:gtk_widget_get_window\
:gtk_widget_grab_focus\
:gtk_widget_hide\
:gtk_widget_hide_on_delete\
:gtk_widget_is_drawable\
:gtk_widget_is_focus\
:gtk_widget_is_sensitive\
:gtk_widget_is_toplevel\
:gtk_widget_map\
:gtk_widget_modify_base\
:gtk_widget_modify_font\
:gtk_widget_modify_text\
:gtk_widget_new\
:gtk_widget_queue_draw\
:gtk_widget_queue_resize\
:gtk_widget_queue_resize_no_redraw\
:gtk_widget_realize\
:gtk_widget_render_icon\
:gtk_widget_reparent\
:gtk_widget_send_expose\
:gtk_widget_set_has_tooltip\
:gtk_widget_set_has_window\
:gtk_widget_set_name\
:gtk_widget_set_sensitive\
:gtk_widget_set_size_request\
:gtk_widget_set_tooltip_text\
:gtk_widget_set_window\
:gtk_widget_show\
:gtk_widget_show_all\
:gtk_widget_size_allocate\
:gtk_widget_size_request\
:gtk_widget_style_get\
:gtk_window_add_accel_group\
:gtk_window_fullscreen\
:gtk_window_get_default_size\
:gtk_window_get_focus\
:gtk_window_get_group\
:gtk_window_get_position\
:gtk_window_get_role\
:gtk_window_get_screen\
:gtk_window_get_size\
:gtk_window_get_type\
:gtk_window_group_add_window\
:gtk_window_group_new\
:gtk_window_has_toplevel_focus\
:gtk_window_list_toplevels\
:gtk_window_maximize\
:gtk_window_move\
:gtk_window_new\
:gtk_window_present\
:gtk_window_present_with_time\
:gtk_window_set_auto_startup_notification\
:gtk_window_set_default_icon_name\
:gtk_window_set_default_size\
:gtk_window_set_destroy_with_parent\
:gtk_window_set_focus\
:gtk_window_set_focus_on_map\
:gtk_window_set_geometry_hints\
:gtk_window_set_icon_name\
:gtk_window_set_modal\
:gtk_window_set_position\
:gtk_window_set_resizable\
:gtk_window_set_role\
:gtk_window_set_skip_taskbar_hint\
:gtk_window_set_title\
:gtk_window_set_transient_for\
:gtk_window_set_type_hint\
:gtk_window_unfullscreen\
:kJSClassDefinitionEmpty\
:localtime_r\
:memchr\
:memcpy\
:memmove\
:memset\
:mkdir\
:mkdtemp\
:mktime\
:notify_init\
:notify_is_initted\
:notify_notification_attach_to_status_icon\
:notify_notification_new\
:notify_notification_set_timeout\
:notify_notification_set_urgency\
:notify_notification_show\
:notify_uninit\
:open\
:pango_attr_foreground_new\
:pango_attr_list_insert\
:pango_attr_list_new\
:pango_attr_list_unref\
:pango_attr_weight_new\
:pango_cairo_show_layout\
:pango_context_get_language\
:pango_context_get_metrics\
:pango_font_description_free\
:pango_font_description_from_string\
:pango_font_description_get_family\
:pango_font_description_get_size\
:pango_font_description_get_size_is_absolute\
:pango_font_description_new\
:pango_font_description_set_weight\
:pango_font_metrics_get_approximate_digit_width\
:pango_font_metrics_unref\
:pango_layout_get_line_readonly\
:pango_layout_get_pixel_size\
:pango_layout_get_text\
:pango_layout_new\
:pango_layout_set_ellipsize\
:pango_layout_set_text\
:pango_layout_set_width\
:raise\
:rand\
:realpath\
:rename\
:seed_context_collect\
:seed_context_create\
:seed_context_unref\
:seed_evaluate\
:seed_exception_to_string\
:seed_init\
:seed_object_call\
:seed_object_get_property\
:seed_script_exception\
:seed_script_new_from_file\
:seed_simple_evaluate\
:seed_value_from_object\
:seed_value_is_function\
:seed_value_is_object\
:seed_value_protect\
:seed_value_unprotect\
:soup_cookie_copy\
:soup_cookie_equal\
:soup_cookie_free\
:soup_cookie_get_type\
:soup_cookie_jar_add_cookie\
:soup_cookie_jar_all_cookies\
:soup_cookie_jar_delete_cookie\
:soup_cookie_jar_get_type\
:soup_cookie_jar_sqlite_new\
:soup_cookie_jar_text_new\
:soup_cookies_free\
:soup_date_to_time_t\
:soup_form_decode\
:soup_form_encode\
:soup_message_get_flags\
:soup_message_headers_append\
:soup_message_headers_get_content_disposition\
:soup_message_headers_get_content_type\
:soup_message_new\
:soup_password_manager_gnome_get_type\
:soup_proxy_resolver_gnome_get_type\
:soup_session_add_feature\
:soup_session_add_feature_by_type\
:soup_session_feature_get_type\
:soup_session_get_feature\
:soup_uri_decode\
:soup_uri_free\
:soup_uri_new\
:soup_uri_new_with_base\
:soup_uri_set_fragment\
:soup_uri_set_path\
:soup_uri_set_query\
:soup_uri_set_query_from_fields\
:soup_uri_set_scheme\
:soup_uri_to_string\
:sprintf\
:sqrtf\
:strchr\
:strcmp\
:strerror\
:strftime\
:strlen\
:strncmp\
:strncpy\
:strrchr\
:strstr\
:strtod\
:strtol\
:strtoul\
:textdomain\
:time\
:unlink\
:webkit_download_cancel\
:webkit_download_get_current_size\
:webkit_download_get_destination_uri\
:webkit_download_get_elapsed_time\
:webkit_download_get_network_response\
:webkit_download_get_progress\
:webkit_download_get_status\
:webkit_download_get_suggested_filename\
:webkit_download_get_total_size\
:webkit_download_get_type\
:webkit_download_get_uri\
:webkit_download_new\
:webkit_download_set_destination_uri\
:webkit_download_start\
:webkit_get_default_session\
:webkit_network_request_get_message\
:webkit_network_request_get_type\
:webkit_network_request_get_uri\
:webkit_network_request_new\
:webkit_network_request_set_uri\
:webkit_network_response_get_message\
:webkit_web_back_forward_list_add_item\
:webkit_web_back_forward_list_clear\
:webkit_web_back_forward_list_get_back_item\
:webkit_web_back_forward_list_get_back_list_with_limit\
:webkit_web_back_forward_list_get_current_item\
:webkit_web_back_forward_list_get_forward_item\
:webkit_web_back_forward_list_get_forward_list_with_limit\
:webkit_web_data_source_get_data\
:webkit_web_data_source_get_initial_request\
:webkit_web_data_source_get_main_resource\
:webkit_web_data_source_get_request\
:webkit_web_data_source_get_subresources\
:webkit_web_frame_get_data_source\
:webkit_web_frame_get_global_context\
:webkit_web_frame_get_network_response\
:webkit_web_frame_get_provisional_data_source\
:webkit_web_frame_get_uri\
:webkit_web_frame_load_request\
:webkit_web_frame_print_full\
:webkit_web_history_item_copy\
:webkit_web_history_item_get_original_uri\
:webkit_web_history_item_get_title\
:webkit_web_history_item_get_uri\
:webkit_web_inspector_inspect_coordinates\
:webkit_web_navigation_action_get_button\
:webkit_web_navigation_action_get_modifier_state\
:webkit_web_navigation_action_get_reason\
:webkit_web_policy_decision_download\
:webkit_web_policy_decision_ignore\
:webkit_web_resource_get_data\
:webkit_web_resource_get_mime_type\
:webkit_web_resource_get_type\
:webkit_web_resource_get_uri\
:webkit_web_settings_new\
:webkit_web_view_can_copy_clipboard\
:webkit_web_view_can_cut_clipboard\
:webkit_web_view_can_go_back\
:webkit_web_view_can_go_forward\
:webkit_web_view_can_paste_clipboard\
:webkit_web_view_can_redo\
:webkit_web_view_can_show_mime_type\
:webkit_web_view_can_undo\
:webkit_web_view_copy_clipboard\
:webkit_web_view_cut_clipboard\
:webkit_web_view_execute_script\
:webkit_web_view_get_back_forward_list\
:webkit_web_view_get_custom_encoding\
:webkit_web_view_get_encoding\
:webkit_web_view_get_hit_test_result\
:webkit_web_view_get_icon_uri\
:webkit_web_view_get_inspector\
:webkit_web_view_get_load_status\
:webkit_web_view_get_main_frame\
:webkit_web_view_get_progress\
:webkit_web_view_get_type\
:webkit_web_view_get_uri\
:webkit_web_view_get_window_features\
:webkit_web_view_go_back\
:webkit_web_view_go_forward\
:webkit_web_view_go_to_back_forward_item\
:webkit_web_view_load_html_string\
:webkit_web_view_load_uri\
:webkit_web_view_mark_text_matches\
:webkit_web_view_open\
:webkit_web_view_paste_clipboard\
:webkit_web_view_redo\
:webkit_web_view_reload\
:webkit_web_view_reload_bypass_cache\
:webkit_web_view_search_text\
:webkit_web_view_select_all\
:webkit_web_view_set_custom_encoding\
:webkit_web_view_set_highlight_text_matches\
:webkit_web_view_set_settings\
:webkit_web_view_set_view_source_mode\
:webkit_web_view_stop_loading\
:webkit_web_view_undo\
:webkit_web_view_unmark_text_matches\
:xmlCheckVersion\
:xmlCleanupParser\
:xmlDocGetRootElement\
:xmlFree\
:xmlFreeDoc\
:xmlFreeTextReader\
:xmlFreeTextWriter\
:xmlGetProp\
:xmlNewChild\
:xmlNewDoc\
:xmlNewDocNode\
:xmlNewTextChild\
:xmlNewTextReaderFilename\
:xmlNewTextWriterDoc\
:xmlNewTextWriterFilename\
:xmlNodeGetContent\
:xmlNodeGetLang\
:xmlParseFile\
:xmlSaveFormatFile\
:xmlSetProp\
:xmlStrEqual\
:xmlStrPrintf\
:xmlStrdup\
:xmlSubstituteEntitiesDefault\
:xmlTextReaderConstName\
:xmlTextReaderExpand\
:xmlTextReaderGetAttribute\
:xmlTextReaderNext\
:xmlTextReaderNodeType\
:xmlTextReaderRead\
:xmlTextReaderValue\
:xmlTextWriterEndDocument\
:xmlTextWriterEndElement\
:xmlTextWriterSetIndent\
:xmlTextWriterSetIndentString\
:xmlTextWriterStartDocument\
:xmlTextWriterStartElement\
:xmlTextWriterStartElementNS\
:xmlTextWriterWriteAttribute\
:xmlTextWriterWriteAttributeNS\
:xmlTextWriterWriteComment\
:xmlTextWriterWriteElement\
:xmlTextWriterWriteElementNS\
:xmlTextWriterWriteFormatAttribute\
:xmlTextWriterWriteFormatString\
:xmlTextWriterWriteString\
:xsltApplyStylesheet\
:xsltCleanupGlobals\
:xsltFreeStylesheet\
:xsltParseStylesheetFile\
:xsltSaveResultToFilename\
 /tools/lib/ld-2.11.3.so /usr/bin/epiphany-browser'
